// Generated by CoffeeScript 2.1.0
var CFX, StoryTodos, actions, mapActionToProps, mapStateToProps, reducers;

import {
  ddbs as dd
} from 'ddeyes';

import React, {
  Component
} from 'react';

import Input from '../../../StoryView/src/components/input';

import List from '../../../StoryView/src/components/list';

import Title from '../../../StoryView/src/components/title';

import {
  prefixDom
} from 'cfx.dom';

import {
  connect
} from 'cfx.react-redux';

import {
  store
} from 'ReduxServ';

({actions, reducers} = store);

import {
  getState
} from './components';

CFX = prefixDom({Title, Input, List, 'div': 'div'});

StoryTodos = class StoryTodos extends Component {
  constructor(props) {
    super(props);
    this.state = {
      filter: props.state.filter
    };
    this;
  }

  componentWillReceiveProps(nextProps) {
    var filter;
    ({filter} = nextProps.state);
    this.setState({filter});
    this;
    return console.log('1');
  }

  render() {
    var c_Input, c_List, c_Title, c_div;
    ({c_div, c_Title, c_Input, c_List} = CFX);
    return c_div({}, c_Title({}), c_Input({
      filter: this.props.state.filter,
      selector: (function(filter) {
        return this.props.actions.filterSave({
          filter: filter
        });
      }).bind(this),
      blur: (function(v) {
        this.props.actions.create({
          todo: v
        });
        // console.log store
        return console.log(store.store.getState().todosRedux.todos);
      }).bind(this)
    }), c_List({
      data: store.store.getState().todosRedux.todos,
      isClick: false,
      str: ' ',
      Delete: (function(key) {
        // console.log key
        console.log(store.store.getState().todosRedux.todos);
        this.props.actions.removeOne({
          id: key
        });
        return console.log({
          data: store.store.getState().todosRedux.todos
        });
      }).bind(this),
      hasClick: function(str) {
        console.log('key:');
        return console.log(str);
      }
    }));
  }

};

mapStateToProps = function(state) {
  return getState(state.todosRedux);
};

mapActionToProps = {
  filterSave: actions.filterSave,
  create: actions.todosCreate,
  removeOne: actions.todosRemoveOne
};

export default connect(mapStateToProps, mapActionToProps, StoryTodos);
