// Generated by CoffeeScript 2.1.1
var CFX, StoryTodos, actions, mapActionToProps, mapStateToProps, reducers;

import {
  ddbs as dd
} from 'ddeyes';

import React, {
  Component
} from 'react';

import Input from '../../../StoryView/src/components/input';

import List from '../../../StoryView/src/components/list';

import Title from '../../../StoryView/src/components/title';

import {
  prefixDom
} from 'cfx.dom';

import {
  connect
} from 'cfx.react-redux';

import {
  store
} from 'ReduxServ';

({actions, reducers} = store);

import {
  getState
} from './components';

CFX = prefixDom({Title, Input, List, 'div': 'div'});

StoryTodos = class StoryTodos extends Component {
  constructor(props) {
    super(props);
    this.state = {
      filter: props.state.filter,
      todos: []
    };
    this;
  }

  componentWillReceiveProps(nextProps) {
    var filter, todos;
    ({filter, todos} = nextProps.state);
    this.setState({filter, todos});
    return this;
  }

  render() {
    var Packet, c_Input, c_List, c_Title, c_div;
    ({c_div, c_Title, c_Input, c_List} = CFX);
    Packet = function(bool, data) {
      console.log("hello");
      return data.reduce((r, c) => {
        return [...r, ...(c.isCompleted === bool ? [c] : [])];
      }, []);
    };
    return c_div({}, c_Title({}), c_Input({
      filter: this.props.state.filter,
      selector: (function(filter) {
        return this.props.actions.filterSave({
          filter: filter
        });
      }).bind(this),
      data: store.store.getState().todosRedux.todos,
      blur: (function(v) {
        return this.props.actions.create({
          todo: v
        });
      }).bind(this)
    }), c_List({
      // data: @state.todos
      data: (function() {
        switch (this.state.filter) {
          case 'active':
            return Packet(false, this.state.todos);
          case 'completed':
            return Packet(true, this.state.todos);
          case 'all':
            return this.state.todos;
        }
      }).call(this),
      styleChange: (function(id, isCompleted) {
        if (isCompleted === true) {
          return {
            textDecorationLine: 'line-through'
          };
        }
      }).bind(this),
      Delete: (function(key) {
        return this.props.actions.removeOne({
          id: key
        });
      }).bind(this),
      Patch: (function(key, value) {
        return this.props.actions.patch({
          id: key,
          todo: value,
          isCompleted: false
        });
      }).bind(this),
      hasClick: (function(key, todo, isCompleted) {
        return this.props.actions.patch({
          id: key,
          todo: todo,
          isCompleted: !isCompleted
        });
      }).bind(this)
    }));
  }

};

mapStateToProps = function(state) {
  return getState(state.todosRedux);
};

mapActionToProps = {
  filterSave: actions.filterSave,
  create: actions.todosCreate,
  removeOne: actions.todosRemoveOne,
  patch: actions.todosPatch,
  save: actions.todosSave
};

export default connect(mapStateToProps, mapActionToProps, StoryTodos);
